<?php
declare(strict_types=1);

// Mixpanel SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

MixpanelUtility::setRegistrar(function (MixpanelUtility $u): void {
    $u->clean = [MixpanelClean::class, 'call'];
    $u->done = [MixpanelDone::class, 'call'];
    $u->make_error = [MixpanelMakeError::class, 'call'];
    $u->feature_add = [MixpanelFeatureAdd::class, 'call'];
    $u->feature_hook = [MixpanelFeatureHook::class, 'call'];
    $u->feature_init = [MixpanelFeatureInit::class, 'call'];
    $u->fetcher = [MixpanelFetcher::class, 'call'];
    $u->make_fetch_def = [MixpanelMakeFetchDef::class, 'call'];
    $u->make_context = [MixpanelMakeContext::class, 'call'];
    $u->make_options = [MixpanelMakeOptions::class, 'call'];
    $u->make_request = [MixpanelMakeRequest::class, 'call'];
    $u->make_response = [MixpanelMakeResponse::class, 'call'];
    $u->make_result = [MixpanelMakeResult::class, 'call'];
    $u->make_point = [MixpanelMakePoint::class, 'call'];
    $u->make_spec = [MixpanelMakeSpec::class, 'call'];
    $u->make_url = [MixpanelMakeUrl::class, 'call'];
    $u->param = [MixpanelParam::class, 'call'];
    $u->prepare_auth = [MixpanelPrepareAuth::class, 'call'];
    $u->prepare_body = [MixpanelPrepareBody::class, 'call'];
    $u->prepare_headers = [MixpanelPrepareHeaders::class, 'call'];
    $u->prepare_method = [MixpanelPrepareMethod::class, 'call'];
    $u->prepare_params = [MixpanelPrepareParams::class, 'call'];
    $u->prepare_path = [MixpanelPreparePath::class, 'call'];
    $u->prepare_query = [MixpanelPrepareQuery::class, 'call'];
    $u->graphql_body = [MixpanelGraphql::class, 'body'];
    $u->graphql_errors = [MixpanelGraphql::class, 'errors'];
    $u->result_basic = [MixpanelResultBasic::class, 'call'];
    $u->result_body = [MixpanelResultBody::class, 'call'];
    $u->result_headers = [MixpanelResultHeaders::class, 'call'];
    $u->transform_request = [MixpanelTransformRequest::class, 'call'];
    $u->transform_response = [MixpanelTransformResponse::class, 'call'];
});
